[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "1.6.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.48"

[[constraint]]
  branch = "master"
  name = "github.com/bramvdbogaerde/go-scp"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.5.0"

[[constraint]]
  branch = "master"
  name = "github.com/secsy/goftp"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"
